<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Locs-MacBook-Pro.local" name="com.currentweather.api.TC_API_0004_Get_current_weather_data_with_INVALID_CityName_and_StateCode" tests="5" failures="1" timestamp="30 May 2021 15:05:10 GMT" time="0.564" errors="0">
  <testcase name="TC_API_0004_InvalidCase__Get_current_data_by_CityName_and_StateCode" time="0.169" classname="com.currentweather.api.TC_API_0004_Get_current_weather_data_with_INVALID_CityName_and_StateCode"/>
  <testcase name="TC_API_0004_InvalidCase__Get_current_data_by_CityName_and_StateCode" time="0.105" classname="com.currentweather.api.TC_API_0004_Get_current_weather_data_with_INVALID_CityName_and_StateCode">
    <failure type="java.lang.AssertionError" message="expected:&lt;404&gt; but was:&lt;200&gt;">
      <![CDATA[java.lang.AssertionError: expected:<404> but was:<200>
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:834)
at org.junit.Assert.assertEquals(Assert.java:645)
at org.junit.Assert.assertEquals(Assert.java:631)
at com.currentweather.api.TC_API_0004_Get_current_weather_data_with_INVALID_CityName_and_StateCode.TC_API_0004_InvalidCase__Get_current_data_by_CityName_and_StateCode(TC_API_0004_InvalidCase__Get_current_data_by_CityName_and_StateCode.java:38)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
    </failure>
  </testcase> <!-- TC_API_0004_InvalidCase__Get_current_data_by_CityName_and_StateCode -->
  <testcase name="TC_API_0004_InvalidCase__Get_current_data_by_CityName_and_StateCode" time="0.099" classname="com.currentweather.api.TC_API_0004_Get_current_weather_data_with_INVALID_CityName_and_StateCode"/>
  <testcase name="TC_API_0004_InvalidCase__Get_current_data_by_CityName_and_StateCode" time="0.100" classname="com.currentweather.api.TC_API_0004_Get_current_weather_data_with_INVALID_CityName_and_StateCode"/>
  <testcase name="TC_API_0004_InvalidCase__Get_current_data_by_CityName_and_StateCode" time="0.091" classname="com.currentweather.api.TC_API_0004_Get_current_weather_data_with_INVALID_CityName_and_StateCode"/>
</testsuite> <!-- com.currentweather.api.TC_API_0004_Get_current_weather_data_with_INVALID_CityName_and_StateCode -->
